redirects:
  javascript/login-and-authentication-for-the-sdk: javascript-login/README.md
  javascript/login-and-authentication-for-the-sdk/playcanvas-login-and-auth-minimal-example: javascript-login/playcanvas-login-and-auth-minimal-example.md
  javascript/login-and-authentication-for-the-sdk/three.js-login-and-auth-minimal-example: javascript-login/three.js-login-and-auth-minimal-example.md
  javascript/storage-sdk: javascript-storage.md
  javascript/leaderboard-sdk: javascript-leaderboard/README.md
  javascript/leaderboard-sdk/playcanvas-leaderboard-minimal-example: javascript-leaderboard/playcanvas-leaderboard-minimal-example.md
  storage-sdk/unity-cloud-minimal-example: legacy-unity-sdk/unity-cloud-minimal-example.md
  login-and-authentication-for-the-sdk/unity-login-and-authentication-minimal-example: legacy-unity-sdk/unity-login-and-authentication-minimal-example.md
  leaderboard-sdk/unity-leaderboard-minimal-example: legacy-unity-sdk/unity-leaderboard-minimal-example.md
